services:
  redis:
    image: redis:7-alpine
    container_name: findra-redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:8.0
    container_name: findra-mongo
    ports:
      - "27017:27017"
    volumes:
      - findra_mongo_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: findra-mongo-express
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"

  whisper:
    build: ./whisper-service
    container_name: findra-whisper
    ports:
      - "8001:8001"
    volumes:
      - whisper_models:/root/.cache

volumes:
  findra_mongo_data:
  whisper_models:
